CREATE DATABASE IF NOT EXISTS EmpleadosBDAritz;
use EmpleadosBDAritz;
CREATE TABLE IF NOT EXISTS EMPLEADO (id INT AUTO_INCREMENT PRIMARY KEY,nombre VARCHAR(50) NOT NULL,puesto VARCHAR(50) NOT NULL,salario int, fecha date);